name: Lucerne FLOW
favicon: null
layout_spectrum: 0.09408459416590631
typography_spectrum: 0.18225323292426765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2983282108325511
  lightness: 0.3359656762331724
  saturation: 0.9479449857026339
  rhythmicContrast: 0.7466865349560976
purpose: []
